[package]
name = "big2"
version = "0.1.0"
authors = ["Ren√© van Dorst"]
edition = "2018"
exclude = ["target", "Cargo.lock"]
license = "MIT"

[dependencies]
rand = "0.7"
crossterm = { version = "0.17", features = ["event-stream"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
pico-args = "0.3.4"
log = "0.4"
simplelog = "0.8"

